# docker-compose.yml
services:
  replay:
    image: batonics-challenge
    build:
      context: .
      dockerfile: Dockerfile
    command: ["replay", "--bind", "0.0.0.0:9000", "--file", "/data/feed.bin", "--chunk", "1048576", "--max-bps", "0"]
    volumes:
      - ./data:/data:ro
    ports:
      - "9000:9000"

  engine:
    image: batonics-challenge
    build:
      context: .
      dockerfile: Dockerfile
    command:
      [
        "run",
        "--connect",
        "replay:9000",
        "--http-bind",
        "0.0.0.0:8080",
        "--out",
        "/data/final_snapshot.json",
        "--depth",
        "50",
        "--snapshot-every-n",
        "250000",
        "--snapshot-interval-ms",
        "250",
        "--once"
      ]
    depends_on:
      - replay
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"
